# Generated by Django 3.2 on 2021-08-09 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0002_jugglingvideo_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugglingvideo',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jugglingvideo',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
