# Generated by Django 3.2 on 2022-01-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0005_videocomment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='vlog.jugglingvideo'),
        ),
    ]
