# Generated by Django 3.2 on 2022-01-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0006_videocomment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='author',
            field=models.TextField(default='anonymous'),
        ),
    ]
