# Generated by Django 3.2 on 2022-01-23 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0007_videocomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
