# Generated by Django 3.2 on 2022-01-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0009_videocomment_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('link', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
