# Generated by Django 3.2 on 2022-02-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0011_jugglingvideo_author_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videocomment',
            unique_together={('text', 'author', 'video')},
        ),
    ]
